language: ruby
rvm:
- 2.1.2
deploy:
  provider: heroku
  api_key:
    secure: wjzp93tGcuBClSja30cHYSJvK9FjL72Z6H0YQ/gqTzP+BOIbjt/yh5oFLpE+wOpinX8oMQNev3mbf9+pL+MdOvqBT3CmPjRkyIQu2mdvw3+l2HOEhqiq+N0k+iVqe6d3Jb7Q8oL/965uFsoRmrqlBrHIhMb23AeoSb3h819rM+o=
  app: quamap
  on:
    repo: projectKUA/quamap
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
